### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by b-m-f**
Typo and a more concise description for backend defaulting on HTTP methods

### CODE REVIEW

**Comment by b-m-f** [comment]
Great readme btw 👏

**Review by jonaslu — APPROVED** [review]
[LGTM](https://miro.medium.com/max/800/1*C-nloJuGJ8xW55Bd0kpk_g.jpeg)

**Comment by jonaslu** [comment]
Why thank yous! Did you get a chance to try it out?

**Comment by b-m-f** [comment]
Not yet. Will do as soon as I'm at a computer again. 
Did the PR on mobile 😄

**Pull request merged**
